# Generated by Django 5.0.7 on 2024-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificaciones',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='descripcion_personal',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='educacion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia_laboral',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades_adicionales',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades_conocimientos',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades_conocimientos_adicionales',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades_experiencia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='intereses',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puesto_actual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='referencias',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_puesto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
