# Generated by Django 5.0.7 on 2024-07-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_ciudad_alter_perfil_pais_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idiomas',
            field=models.ManyToManyField(to='accounts.idioma'),
        ),
    ]
