# Generated by Django 5.0.7 on 2024-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_idiomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estudios',
            field=models.ManyToManyField(to='accounts.estudio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencias',
            field=models.ManyToManyField(to='accounts.experiencia'),
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='Perfiles',
        ),
    ]
