# Generated by Django 5.0.7 on 2024-07-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_laboral', '0002_rename_empleador_ofertalaboral_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertalaboral',
            options={'verbose_name': 'Oferta Laboral', 'verbose_name_plural': 'Ofertas Laborales'},
        ),
        migrations.AlterModelTable(
            name='ofertalaboral',
            table='OfertasLaborales',
        ),
    ]
